import js from '@eslint/js';
import globals from 'globals';

export default [
  js.configs.recommended,
  {
    ignores: [
      'node_modules/**',
      'vendor/**',
      'tmp/**',
      'test/generators/tmp/**',
      'eslint.config.js'
    ]
  },
  {
    files: ['**/*.js'],
    languageOptions: {
      ecmaVersion: 5,
      sourceType: 'script',
      globals: {
        ...globals.browser,
        turnstile: 'readonly',
        Turbolinks: 'readonly'
      }
    },
    rules: {
      'for-direction': 'error',
      'getter-return': 'error',
      'no-mixed-operators': 'error',
      'no-await-in-loop': 'error',
      'no-compare-neg-zero': 'error',
      'no-cond-assign': 'error',
      'no-console': 'warn',
      'no-constant-condition': 'error',
      'no-control-regex': 'error',
      'no-debugger': 'error',
      'no-dupe-args': 'error',
      'no-dupe-keys': 'error',
      'no-duplicate-case': 'error',
      'no-empty': 'error',
      'no-empty-character-class': 'error',
      'no-ex-assign': 'error',
      'no-extra-boolean-cast': 'error',
      'no-extra-parens': 'off',
      'no-extra-semi': 'error',
      'no-func-assign': 'error',
      'no-inner-declarations': ['error', 'both'],
      'no-invalid-regexp': 'error',
      'no-irregular-whitespace': 'error',
      'no-obj-calls': 'error',
      'no-prototype-builtins': 'error',
      'no-regex-spaces': 'error',
      'no-sparse-arrays': 'error',
      'no-template-curly-in-string': 'off',
      'no-unexpected-multiline': 'error',
      'no-unreachable': 'error',
      'no-unsafe-finally': 'error',
      'no-unsafe-negation': 'error',
      'use-isnan': 'error',
      'valid-typeof': 'error',

      // BEST PRACTICES
      'accessor-pairs': 'error',
      'array-callback-return': 'error',
      'block-scoped-var': 'error',
      'consistent-return': 'error',
      curly: 'error',
      'default-case': 'error',
      'dot-location': ['error', 'property'],
      'dot-notation': 'error',
      eqeqeq: 'error',
      'guard-for-in': 'error',
      'no-alert': 'error',
      'no-caller': 'error',
      'no-case-declarations': 'error',
      'no-div-regex': 'error',
      'no-else-return': 'error',
      'no-empty-function': 'error',
      'no-empty-pattern': 'error',
      'no-eq-null': 'error',
      'no-eval': 'error',
      'no-extend-native': 'error',
      'no-extra-bind': 'error',
      'no-extra-label': 'error',
      'no-fallthrough': 'error',
      'no-floating-decimal': 'error',
      'no-global-assign': 'error',
      'no-implicit-coercion': 'error',
      'no-implicit-globals': 'error',
      'no-implied-eval': 'error',
      'no-invalid-this': 'off',
      'no-iterator': 'error',
      'no-labels': 'error',
      'no-lone-blocks': 'error',
      'no-loop-func': 'error',
      'no-magic-numbers': 'off',
      'no-multi-spaces': 'error',
      'no-multi-str': 'error',
      'no-new': 'off',
      'no-new-func': 'error',
      'no-new-wrappers': 'error',
      'no-octal': 'error',
      'no-octal-escape': 'error',
      'no-param-reassign': 'error',
      'no-proto': 'error',
      'no-redeclare': 'error',
      'no-restricted-properties': 'error',
      'no-return-assign': 'error',
      'no-return-await': 'error',
      'no-script-url': 'error',
      'no-self-assign': 'error',
      'no-self-compare': 'error',
      'no-sequences': 'error',
      'no-throw-literal': 'error',
      'no-unmodified-loop-condition': 'error',
      'no-unused-expressions': 'error',
      'no-unused-labels': 'error',
      'no-useless-call': 'error',
      'no-useless-concat': 'error',
      'no-useless-escape': 'error',
      'no-useless-return': 'error',
      'no-void': 'error',
      'no-warning-comments': 'error',
      'no-with': 'error',
      'prefer-promise-reject-errors': 'error',
      radix: 'error',
      'require-await': 'error',
      'vars-on-top': 'error',
      'wrap-iife': 'error',
      yoda: 'error',

      // STRICT MODE - allow function-level strict mode for IIFEs
      strict: ['error', 'function'],

      // VARIABLES
      'no-delete-var': 'error',
      'no-label-var': 'error',
      'no-restricted-globals': 'error',
      'no-shadow': 'error',
      'no-shadow-restricted-names': 'error',
      'no-undef': 'warn',
      'no-undef-init': 'error',
      'no-undefined': 'error',
      'no-unused-vars': 'error',
      'no-use-before-define': 'error',

      // STYLISTIC ISSUES
      'array-bracket-spacing': ['error', 'never'],
      'block-spacing': 'error',
      'brace-style': ['error', 'stroustrup'],
      camelcase: 'error',
      'comma-dangle': ['error', 'never'],
      'comma-spacing': 'error',
      'comma-style': 'error',
      'computed-property-spacing': ['error', 'never'],
      'consistent-this': ['error', 'null'],
      'eol-last': ['error', 'always'],
      'func-call-spacing': ['error', 'never'],
      'func-name-matching': ['error', 'always'],
      'func-style': 'off',
      'function-paren-newline': ['error', 'never'],
      indent: ['error', 2],
      'key-spacing': ['error', {beforeColon: false, afterColon: true}],
      'keyword-spacing': ['error', {after: true}],
      'linebreak-style': ['error', 'unix'],
      'lines-between-class-members': ['error', 'always'],
      'max-depth': ['error', 4],
      'max-len': ['error', 120, 4],
      'max-nested-callbacks': ['error', 3],
      'max-params': ['error', 5],
      'max-statements': ['error', 30],
      'max-statements-per-line': ['error', {max: 2}],
      'multiline-comment-style': ['error', 'starred-block'],
      'new-cap': 'error',
      'new-parens': 'error',
      'no-array-constructor': 'error',
      'no-bitwise': 'error',
      'no-lonely-if': 'error',
      'no-mixed-spaces-and-tabs': 'error',
      'no-multiple-empty-lines': ['error', {max: 1, maxBOF: 0, maxEOF: 0}],
      'no-negated-condition': 'error',
      'no-nested-ternary': 'error',
      'no-new-object': 'error',
      'no-tabs': 'error',
      'no-trailing-spaces': 'error',
      'no-unneeded-ternary': 'error',
      'no-whitespace-before-property': 'error',
      'nonblock-statement-body-position': ['error', 'beside'],
      'object-curly-spacing': ['error', 'never'],
      'operator-assignment': ['error', 'always'],
      'operator-linebreak': 'error',
      'padded-blocks': ['error', 'never'],
      'padding-line-between-statements': [
        'error',
        {blankLine: 'always', prev: '*', next: 'block'},
        {blankLine: 'always', prev: '*', next: 'block'},
        {blankLine: 'always', prev: '*', next: 'class'},
        {blankLine: 'always', prev: '*', next: 'export'},
        {blankLine: 'always', prev: '*', next: 'multiline-block-like'},
        {blankLine: 'always', prev: 'block', next: '*'},
        {blankLine: 'always', prev: 'block-like', next: '*'},
        {blankLine: 'always', prev: 'class', next: '*'},
        {blankLine: 'always', prev: 'default', next: '*'},
        {blankLine: 'always', prev: 'multiline-block-like', next: '*'},
        {blankLine: 'never', prev: 'import', next: 'import'}
      ],
      'quote-props': ['error', 'as-needed'],
      quotes: ['error', 'single'],
      semi: ['error', 'always'],
      'semi-spacing': ['error', {before: false, after: true}],
      'semi-style': ['error', 'last'],
      'space-before-blocks': ['error', 'always'],
      'space-before-function-paren': ['error', 'never'],
      'space-in-parens': ['error', 'never'],
      'space-infix-ops': 'error',
      'space-unary-ops': ['error', {words: true, nonwords: false}],
      'spaced-comment': ['error', 'always'],
      'switch-colon-spacing': ['error', {before: false, after: true}],
      'template-tag-spacing': ['error', 'always'],
      'unicode-bom': ['error', 'never'],
      'wrap-regex': 'error',

      // ES6+ rules - disabled for older browser compatibility
      'no-var': 'off',
      'prefer-const': 'off',
      'prefer-arrow-callback': 'off',
      'prefer-rest-params': 'off',
      'prefer-spread': 'off',
      'prefer-template': 'off'
    }
  }
];
